# elasticsearch config
spring:
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      connection-timeout: 1s
      username:
      password:
      read-timeout: 30s


server:
  port: 80
# server config